In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"E:\Curso Data Science con Python - Numpy & Pandas\Datasets+Data+Science+con+Python+-+Pandas\1.3\Info_pais.csv", encoding = "ISO-8859-1", delimiter = ';')

In [4]:
df

                 País   Poblacion  Renta per capita Esperanza de vida
0       United States   325084756             59939              78,9
1               China  1421021791              8612              76,7
2               Japan   127502725             38214              84,5
3             Germany    82658409             44680              81,2
4               India  1338676785              1980              69,4
..                ...         ...               ...               ...
163             Samoa      195352              4305              73,2
164             Tonga      101998              4193              70,8
165             Palau       17808             16275              73,7
166  Marshall Islands       58058              3517              73,9
167          Kiribati      114158              1626              68,1

[168 rows x 4 columns]

In [5]:
df.head(10)

             País   Poblacion  Renta per capita Esperanza de vida
0   United States   325084756             59939              78,9
1           China  1421021791              8612              76,7
2           Japan   127502725             38214              84,5
3         Germany    82658409             44680              81,2
4           India  1338676785              1980              69,4
5  United Kingdom    66727461             39532              81,2
6          France    64842509             39827              82,5
7          Brazil   207833823              9881              75,7
8           Italy    60673701             32038              83,6
9          Canada    36732095             44841              82,3

In [6]:
df_order = df.sort_values("Esperanza de vida", ascending = True)

In [7]:
df_order

                         País  Poblacion  Renta per capita Esperanza de vida
151  Central African Republic    4596023               424              52,8
149                   Lesotho    2091534              1233              53,7
128                      Chad   15016753               657                54
143              Sierra Leone    7488423               504              54,3
28                    Nigeria  190873244              1969              54,3
..                        ...        ...               ...               ...
13                      Spain   46647428             28175              83,4
8                       Italy   60673701             32038              83,6
34                  Singapore    5708041             56746              83,8
31                  Hong Kong    7306322             46733              84,1
2                       Japan  127502725             38214              84,5

[168 rows x 4 columns]

In [3]:
df = pd.read_csv(r"E:\Curso Data Science con Python - Numpy & Pandas\Datasets+Data+Science+con+Python+-+Pandas\5.3\PEATONES_2020.csv", encoding = "ISO-8859-1", delimiter = ';', index_col=2)

In [4]:
df

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,30/06/2020,22:45:00,565,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:00:00,415,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:15:00,551,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:30:00,456,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:45:00,532,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 288749 entries, PERM_PEA02_PM01 to PERM_PEA19_PM01
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FECHA                    288749 non-null  object
 1   HORA                     288749 non-null  object
 2   PEATONES                 288749 non-null  int64
 3   NÚMERO_DISTRITO          284866 non-null  float64
 4   DISTRITO                 284866 non-null  object
 5   NOMBRE_VIAL              284866 non-null  object
 6   NÚMERO                   284866 non-null  float64
 7   CÓDIGO_POSTAL            284866 non-null  float64
 8   OBSERVACIONES_DIRECCION  284866 non-null  object
 9   LATITUD                  284866 non-null  object
 10  LONGITUD                 284866 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 26.4+ MB

In [7]:
df.iloc[:, [1,3]]

                     HORA  NÚMERO_DISTRITO
IDENTIFICADOR
PERM_PEA02_PM01   0:00:00              1.0
PERM_PEA02_PM01   0:15:00              1.0
PERM_PEA02_PM01   0:30:00              1.0
PERM_PEA02_PM01   0:45:00              1.0
PERM_PEA02_PM01   1:00:00              1.0
...                   ...              ...
PERM_PEA19_PM01  22:45:00              1.0
PERM_PEA19_PM01  23:00:00              1.0
PERM_PEA19_PM01  23:15:00              1.0
PERM_PEA19_PM01  23:30:00              1.0
PERM_PEA19_PM01  23:45:00              1.0

[288749 rows x 2 columns]

In [8]:
df.iloc[[2,4,6], [1,3]]

                    HORA  NÚMERO_DISTRITO
IDENTIFICADOR
PERM_PEA02_PM01  0:30:00              1.0
PERM_PEA02_PM01  1:00:00              1.0
PERM_PEA02_PM01  1:30:00              1.0

In [10]:
df.loc[["PERM_PEA02_PM01", "PERM_PEA19_PM01"], ["FECHA", "HORA", "NOMBRE_VIAL"]]

                      FECHA      HORA       NOMBRE_VIAL
IDENTIFICADOR
PERM_PEA02_PM01  01/01/2020   0:00:00  Calle Fuencarral
PERM_PEA02_PM01  01/01/2020   0:15:00  Calle Fuencarral
PERM_PEA02_PM01  01/01/2020   0:30:00  Calle Fuencarral
PERM_PEA02_PM01  01/01/2020   0:45:00  Calle Fuencarral
PERM_PEA02_PM01  01/01/2020   1:00:00  Calle Fuencarral
...                     ...       ...               ...
PERM_PEA19_PM01  30/06/2020  22:45:00      Calle Bailén
PERM_PEA19_PM01  30/06/2020  23:00:00      Calle Bailén
PERM_PEA19_PM01  30/06/2020  23:15:00      Calle Bailén
PERM_PEA19_PM01  30/06/2020  23:30:00      Calle Bailén
PERM_PEA19_PM01  30/06/2020  23:45:00      Calle Bailén

[29036 rows x 3 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 288749 entries, PERM_PEA02_PM01 to PERM_PEA19_PM01
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FECHA                    288749 non-null  object
 1   HORA                     288749 non-null  object
 2   PEATONES                 288749 non-null  int64
 3   NÚMERO_DISTRITO          284866 non-null  float64
 4   DISTRITO                 284866 non-null  object
 5   NOMBRE_VIAL              284866 non-null  object
 6   NÚMERO                   284866 non-null  float64
 7   CÓDIGO_POSTAL            284866 non-null  float64
 8   OBSERVACIONES_DIRECCION  284866 non-null  object
 9   LATITUD                  284866 non-null  object
 10  LONGITUD                 284866 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 34.5+ MB

In [12]:
df.head().info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, PERM_PEA02_PM01 to PERM_PEA02_PM01
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   FECHA                    5 non-null      object
 1   HORA                     5 non-null      object
 2   PEATONES                 5 non-null      int64
 3   NÚMERO_DISTRITO          5 non-null      float64
 4   DISTRITO                 5 non-null      object
 5   NOMBRE_VIAL              5 non-null      object
 6   NÚMERO                   5 non-null      float64
 7   CÓDIGO_POSTAL            5 non-null      float64
 8   OBSERVACIONES_DIRECCION  5 non-null      object
 9   LATITUD                  5 non-null      object
 10  LONGITUD                 5 non-null      object
dtypes: float64(3), int64(1), object(7)
memory usage: 480.0+ bytes

In [13]:
df.describe()

            PEATONES  NÚMERO_DISTRITO         NÚMERO  CÓDIGO_POSTAL
count  288749.000000    284866.000000  284866.000000  284866.000000
mean      451.462717         2.648821      27.223291   28010.099685
std       366.233137         2.999428      24.671669       4.296056
min         1.000000         1.000000       1.000000   28001.000000
25%       142.000000         1.000000       4.000000   28005.000000
50%       373.000000         1.000000      22.000000   28012.000000
75%       680.000000         2.000000      37.000000   28013.000000
max      4759.000000        10.000000      91.000000   28015.000000

In [14]:
df = pd.read_csv(r"E:\Curso Data Science con Python - Numpy & Pandas\Datasets+Data+Science+con+Python+-+Pandas\5.3\PEATONES_2020.csv", encoding = "ISO-8859-1", delimiter = ';', index_col=2)

In [15]:
df

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,30/06/2020,22:45:00,565,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:00:00,415,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:15:00,551,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:30:00,456,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:45:00,532,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 288749 entries, PERM_PEA02_PM01 to PERM_PEA19_PM01
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FECHA                    288749 non-null  object
 1   HORA                     288749 non-null  object
 2   PEATONES                 288749 non-null  int64
 3   NÚMERO_DISTRITO          284866 non-null  float64
 4   DISTRITO                 284866 non-null  object
 5   NOMBRE_VIAL              284866 non-null  object
 6   NÚMERO                   284866 non-null  float64
 7   CÓDIGO_POSTAL            284866 non-null  float64
 8   OBSERVACIONES_DIRECCION  284866 non-null  object
 9   LATITUD                  284866 non-null  object
 10  LONGITUD                 284866 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 26.4+ MB

In [20]:
df["PEATONES"].info()

<class 'pandas.core.series.Series'>
Index: 288749 entries, PERM_PEA02_PM01 to PERM_PEA19_PM01
Series name: PEATONES
Non-Null Count   Dtype
--------------   -----
288749 non-null  int64
dtypes: int64(1)
memory usage: 4.4+ MB

In [21]:
df["PEATONES"].mean()

451.4627167539974

In [22]:
df.describe()

            PEATONES  NÚMERO_DISTRITO         NÚMERO  CÓDIGO_POSTAL
count  288749.000000    284866.000000  284866.000000  284866.000000
mean      451.462717         2.648821      27.223291   28010.099685
std       366.233137         2.999428      24.671669       4.296056
min         1.000000         1.000000       1.000000   28001.000000
25%       142.000000         1.000000       4.000000   28005.000000
50%       373.000000         1.000000      22.000000   28012.000000
75%       680.000000         2.000000      37.000000   28013.000000
max      4759.000000        10.000000      91.000000   28015.000000

In [28]:
print(f"La fecha minima es {df["FECHA"].min()} y la fecha maxima es {df["FECHA"].min()}")

La fecha minima es 01/01/2020 y la fecha maxima es 01/01/2020

In [29]:
print("La fecha minima es {0} y la fecha maxima es {1}".format(df["FECHA"].min(), df["FECHA"].max()))

La fecha minima es 01/01/2020 y la fecha maxima es 31/05/2020

In [34]:
df["SUM_PEATONES"] = df["PEATONES"].cumsum()
#for p in df["PEATONES"]:
#    df["SUM_PEATONES"] += p

In [35]:
df

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD,SUM_PEATONES
IDENTIFICADOR,,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917",497
PERM_PEA02_PM01,01/01/2020,0:15:00,244,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917",741
PERM_PEA02_PM01,01/01/2020,0:30:00,179,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917",920
PERM_PEA02_PM01,01/01/2020,0:45:00,174,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917",1094
PERM_PEA02_PM01,01/01/2020,1:00:00,131,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917",1225
...,...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,30/06/2020,22:45:00,565,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371",130357454
PERM_PEA19_PM01,30/06/2020,23:00:00,415,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371",130357869
PERM_PEA19_PM01,30/06/2020,23:15:00,551,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371",130358420
PERM_PEA19_PM01,30/06/2020,23:30:00,456,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371",130358876
PERM_PEA19_PM01,30/06/2020,23:45:00,532,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371",130359408

In [35]:
df = pd.read_csv(r"E:\Curso Data Science con Python - Numpy & Pandas\Datasets+Data+Science+con+Python+-+Pandas\5.5\PEATONES_2020_mod.csv", encoding = "ISO-8859-1", delimiter = ';', index_col=2)

In [36]:
df.head()

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 288755 entries, PERM_PEA02_PM01 to PERM_PEA19_PM01
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FECHA                    288755 non-null  object
 1   HORA                     288755 non-null  object
 2   PEATONES                 288752 non-null  float64
 3   NÚMERO_DISTRITO          284872 non-null  float64
 4   DISTRITO                 284872 non-null  object
 5   NOMBRE_VIAL              284872 non-null  object
 6   NÚMERO                   284872 non-null  float64
 7   CÓDIGO_POSTAL            284872 non-null  float64
 8   OBSERVACIONES_DIRECCION  284872 non-null  object
 9   LATITUD                  284872 non-null  object
 10  LONGITUD                 284872 non-null  object
dtypes: float64(4), object(7)
memory usage: 26.4+ MB

In [38]:
type(df)

pandas.core.frame.DataFrame

In [39]:
df.shape
original_rows = df.shape[0]
print(f"Número de filas: {original_rows}")

Número de filas: 288755

In [40]:
df.drop_duplicates()

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,30/06/2020,22:45:00,565.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:00:00,415.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:15:00,551.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:30:00,456.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:45:00,532.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [41]:
df.shape

(288755, 11)

In [42]:
df.drop_duplicates(inplace=True)

In [43]:
df.shape
filas_sin_duplicar = df.shape[0]
duplicated_rows = original_rows-df.shape[0]

In [44]:
print(f"Número de filas totales: {original_rows}, de las cuales hay {duplicated_rows} filas duplicadas")

Número de filas totales: 288755, de las cuales hay 6 filas duplicadas

In [45]:
df.dropna(inplace=True)

In [46]:
df.shape
wrong_rows = original_rows-df.shape[0]

In [47]:
print(f"Número de filas totales sin duplicar: {filas_sin_duplicar}, de las cuales hay {wrong_rows} filas erroneas")

Número de filas totales sin duplicar: 288749, de las cuales hay 3892 filas erroneas

print(f"El {round((wrong_rows/original_rows)*100, 4)} % de los registros son erroneos")

In [112]:
df2= pd.read_csv(r"E:\Curso Data Science con Python - Numpy & Pandas\Datasets+Data+Science+con+Python+-+Pandas\5.5\PEATONES_2020_mod.csv", encoding = "ISO-8859-1", delimiter = ';', index_col=2)

In [113]:
df2.head()

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"

In [114]:
df2[(df2["FECHA"] >= "01/01/2020") & (df2["FECHA"] <= "01/05/2020")]

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,01/05/2020,22:45:00,568.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:00:00,588.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:15:00,504.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:30:00,554.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:45:00,492.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [115]:
df_filtered = df2[df2["FECHA"] >= "01/05/2020"]
df_filtered

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,02/01/2020,0:00:00,406.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,02/01/2020,0:15:00,273.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,02/01/2020,0:30:00,208.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,02/01/2020,0:45:00,250.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,02/01/2020,1:00:00,144.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,30/06/2020,22:45:00,565.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:00:00,415.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:15:00,551.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:30:00,456.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:45:00,532.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [116]:
type(df2["DISTRITO"].str)

pandas.core.strings.accessor.StringMethods

In [117]:
df2[df2["DISTRITO"].str.contains('Centro', regex=False, na = False)]

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,30/06/2020,22:45:00,565.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:00:00,415.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:15:00,551.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:30:00,456.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,30/06/2020,23:45:00,532.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [118]:
df2 = df2[(df2["FECHA"] >= "01/01/2020") & (df2["FECHA"] <= "01/05/2020") & (df2["DISTRITO"].str.contains('Centro', regex=False, na = False))]
df2

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...
PERM_PEA19_PM01,01/05/2020,22:45:00,568.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:00:00,588.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:15:00,504.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:30:00,554.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
PERM_PEA19_PM01,01/05/2020,23:45:00,492.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [199]:
total_rows = len(df2.index)
total_rows
df_interpolate = None
if total_rows - int(df2.count()["PEATONES"]) > 0:
    print("Hay valores nulos")
    df2["PEATONES"].fillna(value=round(df2["PEATONES"].mean()), inplace=True)
df2["PEATONES"].mean()

443.6867516415604

In [198]:
df2.head(10)
#df_interpolate = df2.interpolate(method='linear', limit_direction = 'forward')

,FECHA,HORA,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
IDENTIFICADOR,,,,,,,,,,,
PERM_PEA02_PM01,01/01/2020,0:00:00,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:15:00,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:30:00,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,0:45:00,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:00:00,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:15:00,95.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:30:00,444.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,1:45:00,175.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,2:00:00,149.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
PERM_PEA02_PM01,01/01/2020,2:15:00,126.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,0",0

In [5]:
df_flowers = pd.read_csv(r"E:\Curso Data Science con Python - Numpy & Pandas\Datasets+Data+Science+con+Python+-+Pandas\5.12\iris_dataset.csv", encoding = "ISO-8859-1", delimiter = ',')

In [7]:
df_flowers

,longitud_sépalo,anchura_sépalo,longitud_pétalo,anchura_pétalo,clase
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [32]:
df_flowers = df_flowers.drop('clase', axis=1)
df_flowers

,longitud_sépalo,anchura_sépalo,longitud_pétalo,anchura_pétalo,Area_petalo
0,5.1,3.5,1.4,0.2,0.879646
1,4.9,3.0,1.4,0.2,0.879646
2,4.7,3.2,1.3,0.2,0.816814
3,4.6,3.1,1.5,0.2,0.942478
4,5.0,3.6,1.4,0.2,0.879646
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,37.573448
146,6.3,2.5,5.0,1.9,29.845130
147,6.5,3.0,5.2,2.0,32.672564
148,6.2,3.4,5.4,2.3,39.018581
149,5.9,3.0,5.1,1.8,28.839821

In [21]:
df_new = pd.DataFrame(data=(np.pi * df_flowers["longitud_pétalo"] * df_flowers["anchura_pétalo"]), columns=["Area"])

In [22]:
df_new["longitud_pétalo (mm)"] = df_flowers["longitud_pétalo"]
df_new["anchura_pétalo (mm)"] = df_flowers["anchura_pétalo"]

In [23]:
df_new

          Area  longitud_pétalo (mm)  anchura_pétalo (mm)
0     0.879646                   1.4                  0.2
1     0.879646                   1.4                  0.2
2     0.816814                   1.3                  0.2
3     0.942478                   1.5                  0.2
4     0.879646                   1.4                  0.2
..         ...                   ...                  ...
145  37.573448                   5.2                  2.3
146  29.845130                   5.0                  1.9
147  32.672564                   5.2                  2.0
148  39.018581                   5.4                  2.3
149  28.839821                   5.1                  1.8

[150 rows x 3 columns]

In [25]:
df_flowers["Area_petalo"] = df_flowers.apply(lambda x: (np.pi * x["longitud_pétalo"] * x["anchura_pétalo"]), axis=1)

In [27]:
df_flowers

,longitud_sépalo,anchura_sépalo,longitud_pétalo,anchura_pétalo,clase,Area_petalo
0,5.1,3.5,1.4,0.2,Iris-setosa,0.879646
1,4.9,3.0,1.4,0.2,Iris-setosa,0.879646
2,4.7,3.2,1.3,0.2,Iris-setosa,0.816814
3,4.6,3.1,1.5,0.2,Iris-setosa,0.942478
4,5.0,3.6,1.4,0.2,Iris-setosa,0.879646
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,37.573448
146,6.3,2.5,5.0,1.9,Iris-virginica,29.845130
147,6.5,3.0,5.2,2.0,Iris-virginica,32.672564
148,6.2,3.4,5.4,2.3,Iris-virginica,39.018581
149,5.9,3.0,5.1,1.8,Iris-virginica,28.839821

In [29]:
df_flowers["Area_petalo"].median()

17.64004274990669

In [30]:
# ¿Qué valor de área solo es superado por el 10% de los petalos?
df_flowers["Area_petalo"].quantile(0.9)

38.93375775593831

In [33]:
df_flowers.corr()

,longitud_sépalo,anchura_sépalo,longitud_pétalo,anchura_pétalo,Area_petalo
longitud_sépalo,1.000000,-0.109369,0.871754,0.817954,0.857326
anchura_sépalo,-0.109369,1.000000,-0.420516,-0.356544,-0.280612
longitud_pétalo,0.871754,-0.420516,1.000000,0.962757,0.958472
anchura_pétalo,0.817954,-0.356544,0.962757,1.000000,0.980229
Area_petalo,0.857326,-0.280612,0.958472,0.980229,1.000000